### PR TITLE
fix(types): Add `false` to accepted `scrollBehavior` values

### PR DESCRIPTION
**Pull request by Andarist**
This is what is supported in the Cypress itself

### CODE REVIEW

**Comment by dmtrKovalenko** [comment]
Unfortunately no. This won't work here as in cypress because in cypress it will click button without scrolling, this is possible only for fake js events

**Comment by Andarist** [comment]
My use is actually covered by this PR and I've successfully used `scrollBehavior: false` with the current release - I just had to add `// @ts-expect-error` since this is not allowed according to the typings.

Use case:
1. scroll "manually" by setting `scrollTop` to the value I want
2. the element that I intend to clicked gets partially visible in a scrollable container
3. click on the top of the element

Without suppressing the auto-scroll in here the clicking has been scrolling to my element (and using `scrollBehavior: 'top'` didn't help) and messing up my scenario that I've needed to cover as the scroll position is influencing my app's logic.

**Comment by Andarist** [comment]
@dmtrKovalenko friendly 🏓

**Review by dmtrKovalenko — APPROVED** [review]

**Pull request merged**
