### PR TITLE
Add support for x/y options to realMouseDown and realMouseUp.

### PR DESCRIPTION
**Pull request by maxbogue**
https://github.com/dmtrKovalenko/cypress-real-events/issues/316

This is what I've ended up using in a forked version of realMouseDown in my project for testing some canvas interactions. Let me know if there's anything else I need to add!

### CODE REVIEW

**Comment by dmtrKovalenko** [comment]
But position itself can have x and y

**Comment by maxbogue** [comment]
You said that was relative to the tab and not the element though correct? I was trying to make it easy to use realMouseDown and realMouseUp the same as realMouseMove.

**Comment by dmtrKovalenko** [comment]
Let's name them differently e.g. relative position because it is confusing

**Comment by maxbogue** [comment]
Other options: `{ relativeX, relativeY }`, `{ deltaX, deltaY }`, `{ offsetX, offsetY }`.

**Review by dmtrKovalenko — COMMENTED** [review]
Oh god I do not remember how the x y works, looks like relative position :)

That's my bad. Can you please try with the provided one and check if it works different because it looks like it should do the same job

**Comment by maxbogue** [comment]
😭 Pain, it does work. Maybe the docs could be updated to make that clearer? Everywhere I saw about `position` only listed the 9 string options so I didn't know I could do that.

**Comment by dmtrKovalenko** [comment]
I'm sorry man, for your contribution anyway! We can get the docs update within this pr so you have contribution counted

**Comment by maxbogue** [comment]
I'll look into it tomorrow.

**Pull request closed without merging**
